GUI의 아이템을 Rewards.yml 양식에 맞게 커스텀 가능하게끔 하기
MineFactory-Resource/DailyReward pull request #1
Opened 2022-09-27 11:55 UTC by Fade-Jung

![image](https://user-images.githubusercontent.com/71818357/192517701-567dd56e-62c5-4e0d-a8f6-155f127a2b60.png)
기본 Rewards.yml 의 파일.

![image](https://user-images.githubusercontent.com/71818357/192517802-db0f555f-65cb-4583-ba1c-502ca6ec6bb3.png)
적용 되는 출석체크의 GUI

![image](https://user-images.githubusercontent.com/71818357/192518391-e9a306dd-6b7b-4472-a134-e56ba58e1074.png)
커스텀을 한 Rewards.yml의 파일

![image](https://user-images.githubusercontent.com/71818357/192518445-e8e58c3b-2608-4d44-a068-e89dfb47405f.png)
커스텀이 적용되는 출석체크의 GUI

![image](https://user-images.githubusercontent.com/71818357/192518512-381ffd16-1287-44dd-884b-1e5e732d78f9.png)

![image](https://user-images.githubusercontent.com/71818357/192518535-7de7c702-0541-4cd7-abab-f524db766ac9.png)
그리고 커스텀이 된 아이템의 모습

2022-09-27 12:10 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +            dailyItem.putAll(RewardManager.getRewards("Rewards"));
출석체크 명령어를 입력할 때마다 map에 정보를 담는 건 안 좋은 것 같습니다. 플러그인이 활성화 될 때 한 번 정보를 담으면 좋을 것 같아요

2022-09-27 12:10 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +            for (Map.Entry<Integer, ItemStack> dailyitems : dailyItem.entrySet()){
여기도 명령어를 입력할 때 마다 보상을 설정하는 것은 안 좋은 것 같습니다.

2022-09-27 12:10 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/ClickEvent.java
> +    public void clickEvent(InventoryClickEvent e) {
출석체크 GUI의 인벤토리일 때만 캔슬되도록 해주세요.

2022-09-27 12:24 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/ClickEvent.java
> +    public void clickEvent(InventoryClickEvent e) {
InventoryClickEvent 뿐만이 아니라 InventoryDragEvent도 캔슬되도록 해주세요!

2022-09-27 12:27 UTC, tjrhuni commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +            for (Map.Entry<Integer, ItemStack> dailyitems : dailyItem.entrySet()){
보상 아이템에 addItemFlags(ItemFlag.HIDE_ATTRIBUTES) 메소드를 사용하여 아이템의 Attributes 들을 안 보이게 하면 좋을 것 같습니다.

2022-09-27 14:41 UTC, abelbaek commented
테스트 전혀 안한거같은데 테스트하고 PR올리세요

2022-09-27 14:41 UTC, abelbeak commented
리뷰어는 개발자 전부 다세요

2022-09-27 14:42 UTC, abelbeak commented
PR 먼저 올린 뒤에 작업 시작하고, 작업이 완료되지 않은 PR은 WIP 태그나 Draft PR로 올리세요

2022-09-29 11:01 UTC, Fade-Jung commented
DailyReward 테스트 케이스:
* 플러그인이 처음 켜졌을 때, 기본 reward.yml에 있는 1일차 보상이 GUI에 잘 들어가는지 확인하기.
* reward.yml에 보상을 수정하고 리로드가 되었을 때, 출석체크 GUI가 수정이 됐는지 확인하기. (아이템 이름, 아이템 로어, 아이템 타입, 아이템의 슬롯칸)
* 출석체크 GUI안의 아이템들이 클릭이나, 드래그를 했을 때, 다른 GUI칸으로 이동이 안되는지 확인하기.
* 출석체크 GUI안의 아이템이 도구나 갑옷일때, 그 아이템의 속성이 뜨는지 확인하기.(ex : 7 공격피해, 1.1 공격 속도, 3 방어 등등...)

![image](https://user-images.githubusercontent.com/71818357/193012139-f42d5d26-0d54-45a9-8ee6-f08d72f95a13.png)
![image](https://user-images.githubusercontent.com/71818357/193013966-4b5e61b5-7a45-464f-8d4b-e5b7219d6829.png)

결과 :
* 처음 켜졌을 때, 기본 reward.yml에 있는 1일차 보상이 GUI에 잘 들어갔는지 확인이 되었습니다.
* 서버가 리로드 되었을 때 출석체크 GUI가 잘 수정이 된것을 확인했습니다.
* 출석체크 GUI안의 아이템을 클릭이나, 드래그를 했을때 다른 GUI칸으로 이동이되거나, 플레이어의 인벤토리로 옮기는게 안되는것을 확인했습니다.
* 수정된 출석체크 GUI의 아이템이 도구나, 갑옷일 때, 아이템의 속성 (ex : 7 공격피해, 1.1 공격 속도, 3 방어 등등...)이 뜨지 않는것을 확인했습니다.

2022-09-29 14:27 UTC, tjrhuni commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +        RewardManager rm = new RewardManager();
플러그인이 비활성화될 때 rewards.yml이 리로드되고 저장되어야 하는 이유가 있을까요?

2022-09-29 14:27 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +            player.openInventory(RewardManager.DailyRewardGui);
RewardManager를 그때그때 불러서 사용하는 것이 아닌 필드로 선언하면 좋을 것 같아요

2022-09-29 14:27 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +    private static final Map<Integer, ItemStack> dailyItem = new HashMap<>();
여기 필드들이 static으로 선언되어야하는 이유가 있을까요?

2022-09-30 05:58 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +        RewardManager rm = new RewardManager();
플러그인이 비활성화 되기전에 rewards.yml을 수정을 했을 때, rewards.yml이 이전으로 되돌아가는걸 막기 위함입니다.

2022-09-30 07:31 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +        RewardManager rm = new RewardManager();
rewards.yml을 수정하고 나서 ctrl+s 혹은 다른 저장 방법을 써서 수동으로 저장을 하고 리로드를 해서 변경된 값을 반영할 텐데, 플러그인이 비활성화될 때 rewards.yml이 이전으로 되돌아지 않을텐데요? onDisable 메소드에서 리로드하는 코드와 저장하는 코드를 없앤 후에 이전으로 되돌아가는지 테스트 해보셨나요?

2022-09-30 07:34 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +        RewardManager rm = new RewardManager();
onCommand 메소드를 살펴보았는데 리로드 명령어 기능이 구현되어 있지 않은데.. 테스트 케이스에서 언급된 리로드가 혹시 /reload 명령어인가요..?

2022-09-30 08:16 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +        RewardManager rm = new RewardManager();
예 아직 리로드 명령어 기능이 구현되어있지 않아서 현재 언급된 리로드는 /reload 가 맞습니다.

일단은 리로드하는 코드와, 저장하는 코드를 둘다 뺐을때는 이전으로 되돌아가나
저장하는 코드만 넣었을땐 이전으로 되돌아갑니다.

2022-09-30 08:19 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +    private static final Map<Integer, ItemStack> dailyItem = new HashMap<>();
static으로 선언되어야 할 이유가 없네요, 첨삭하겠습니다.

2022-09-30 08:28 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +        RewardManager rm = new RewardManager();
제 생각에는 /reload 명령어로 플러그인을 리로드 하려해서 이전으로 되돌아가는 것 같습니다. /reload 명령어는 rewards.yml을 reload 해주지 않기 때문입니다. 그렇기 때문에, 플러그인이 비활성화될 때 리로드를 한 번 해주고 저장을 해주어야 하는 것이라 생각됩니다. 리로드 명령어를 구현하신 후 다시 한 번 테스트 해주세요. 그리고 앞으로는 /reload 명령어를 사용하지 말아주세요. 해당 명령어는 여러 문제들을 일으킬 수 있습니다..

2022-09-30 08:31 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +        RewardManager rm = new RewardManager();
/reload 가 지금으로선 확실하게 문제가 있다고는 말은 못하겠는데,
쓰지 말라고 수십번 말하는데 계속 쓰는 이유가 뭐임?

2022-09-30 08:32 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +        RewardManager rm = new RewardManager();
DailyRewards의 리로드 명령어 기능이 구현되어있지않아 임시로 /reload를 사용했었습니다....
지금 리로드 명령어 기능을 추가해서 커밋할 예정입니다.

2022-09-30 09:02 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +        RewardManager rm = new RewardManager();
추가적으로 리로드 기능을 추가했습니다.

리로드 명령어 테스트 케이스 : 
* rewards.yml 을 수정을 하고 /dailyreward reload 명령어를 통해 리로드를 했을 때 적용이 잘 되는가?

![image](https://user-images.githubusercontent.com/71818357/193234422-961c5ed9-809a-4153-bffd-56df99775ebd.png)
결과 : 리로드 기능을 통해 dailyreward 리로드 했을 때, 정상적으로 GUI에 reward.yml 수정 된것이 적용된것을 확인했습니다.

2022-09-30 09:24 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +                    rm.save();
리로드 후 save는 따로 안 해주셔도 돼요

2022-09-30 09:24 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +    private static final Set<ItemMeta> dailyItemMetaSet = new HashSet<>();
여기 아직 static으로 선언된 필드들이 있네요

2022-09-30 09:28 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +                    rm.save();
확인했습니다.

2022-10-01 10:52 UTC, LesserJang requested changes

2022-10-01 10:52 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +    public final Inventory DailyRewardGui = Bukkit.createInventory(null, 54, ChatColor.GREEN + "출석체크 GUI");
camelCase 작명법 사용해주세요

2022-10-01 10:52 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +        Set<String> rewardsKeys = getConfig().getConfigurationSection(path).getKeys(false);
같은 객체 내에서 인스턴스 변수를 사용하실때는 선언되어있는 getter 메소드보다는 직접 변수에 엑세스해주세요. 여기서부터 아래에 getConfig() 가 많이 보이는데 모두 this.rewardsFile 로 바꿔주시면 됩니다.

2022-10-01 10:52 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +            throw new IllegalArgumentException("rewards.yml 에서 문제가 발생했습니다.");
이런 오류 메시지는 이게 왜 오류가 나왔는지 알려주는 것이 목적입니다. 콘솔에 오류가 나서 봤는데 문제가 발생했다고만 적혀있으면 뭐가 문제고, 문제를 뭐 어떻게 수정해야되는지 알 수 없어요. 예를 들어서 rewards.yml 파일의 보상 내용이 비어있습니다. 라고 뭐가 문제인지 정확하게 알려주는게 좋습니다.

2022-10-01 10:52 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +            }
NPE는 catch 로 잡기 보다는 NPE가 뜰 수 있는 부분들에 모두 if 문으로 null 체크를 하는것이 좋습니다.

2022-10-01 10:52 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +                for (String commands : getConfig().getStringList(path + "." + key + ".commands")){
String 연산은 생각보다 많은 코스트가 소모됩니다. getConfig().getConfigurationSection(path); 메소드로 Section 객체를 변수에 저장해두고, section.getString("item_type") 이런식으로 가져오는게 훨씬 빨라요.

2022-10-01 12:03 UTC, LesserJang approved these changes

2022-10-01 12:54 UTC, Seokhun-Yang approved these changes

2022-10-02 08:55 UTC, merged