아이템을 눌렀을 때, 명령어가 실행되게끔 하기.
MineFactory-Resource/DailyReward pull request #2
Opened 2022-10-05 11:17 UTC by Fade-Jung

테스트 케이스 :
* GUI의 아이템을 클릭했을 때, rewards.yml에서 설정한 명령어가 잘 실행되나 확인하기
* 명령어가 여러줄로 설정을 했을 때, 순차적으로 실행되는지 확인하기
* 플레이어의 권한을 뺐을 때도 GUI의 아이템을 클릭했을 때 권한이 필요한 명령어가 실행이 잘 작동되는지 확인하기.

![image](https://user-images.githubusercontent.com/71818357/194047827-4ce7b5d8-a9ec-4d64-8ef2-1028fd2f5dc8.png)

![image](https://user-images.githubusercontent.com/71818357/194047796-0896cf2f-b678-48da-b9e8-2d41093444a4.png)

![image](https://user-images.githubusercontent.com/71818357/194047948-a5a2e3a0-c643-4835-9bdd-876088d08876.png)

결과 : 
* "day3"에 설정된 commands 의 목록들이 두번째 사진처럼 순차적으로 실행이 잘 되는것을 확인.
* 관리자 권한을 뺐을 때도 GUI의 아이템을 클릭했을 때, 권한이 필요한 명령어라도 실행이 잘 되는것을 확인.

2022-10-07 09:00 UTC, Seokhun-Yang requested changes

2022-10-07 09:00 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/ClickEvent.java
> +    public ConfigurationSection loadConfiguration() {
ClickEvent 생성자에서 RewardManager 클래스를 매개변수로 받는 것이 아닌, 메인 클래스를 받도록 수정을 하신 후. 메인 클래스에 RewardManager 클래스를 필드로 선언하고 getter를 사용해서 RewardManager 클래스의 FileConfiguration에 접근할 수 있도록하면 좋을 것 같습니다. 아래 clickEvent 메소드에 있는 for 구문을 보니 수정이 필요할 것 같다는 생각이 들어요. for 구문이 동작될 때마다 rewards.yml를 리로드하는 것과 마찬가지여서.. 위에 말씀드린 방법으로 수정해주세요.

2022-10-09 12:50 UTC, Seokhun-Yang requested changes

2022-10-09 12:50 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/ClickEvent.java
> +    public ClickEvent(Dailyreward dailyreward) {
생성자에서 매개변수로 선언하셨으면 사용을 해주세요

2022-10-09 12:50 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +    public YamlConfiguration rewardsYmlLoad() {
for문이 반복될 때마다 rewards.yml이 리로드 되는 것은 수정하셨지만, 메소드가 호출될 때마다 리로드 되는 것은 수정하지 않으셨네요.. RewardManager 클래스에 선언되어 있는 FileConfiguration 필드를 리턴해주는 메소드를 만드셔서 메소드가 호출될 때마다 리로드 되는 것을 수정해주세요.

2022-10-13 10:40 UTC, kari0707 approved these changes

2022-10-13 10:42 UTC, Seokhun-Yang approved these changes

2022-10-13 11:30 UTC, merged