보상을 수령받고 나서 한번더 보상을 못받게하고, 누적일차에 맞게 수령받을 수 있게 하기
MineFactory-Resource/DailyReward pull request #4
Opened 2022-10-21 11:33 UTC by Fade-Jung

**테스트 케이스들의 테스트 환경**
>1. 테스트 서버 버킷 : purpur-1.18.2-1632.jar
>2. 테스트한 마인크래프트 버전 : 1.18.2

**테스트 케이스 1**

확인 해야 하는것 : 
>플레이어가 서버에 접속했을때, 플러그인 폴더 안에 Players 폴더가 생성된 뒤
> 플레이어 데이터 파일(YAML)이 잘 생성되고
> 파일 안의 내용이 기본적으로 생성되었나의 여부

실행한 단계 : 
>1. 테스트 서버의 plugins 폴더 안에 DailyReward 플러그인을 넣은뒤에 서버 열기.  
>2. 테스트 서버에 접속.

예상 결과 :
> plugins\Dailyreward\Players 폴더 안에 플레이어의 데이터 파일이 생성되고, 내용이 기본적으로 생성되어야함.

실제 결과 :
> 예상 결과랑 같은 결과가 나온 것을 확인. [통과]

첨부 사진 :
> ![image](https://user-images.githubusercontent.com/71818357/197181139-e862d275-b0f2-467f-bdfa-0c866fa9088e.png)
↑ plugins\Dailyreward\Players 폴더 안에 플레이어의 데이터 파일
> ![image](https://user-images.githubusercontent.com/71818357/197181068-257d53c4-ad74-4a97-a779-c96e501fc16c.png)
↑ 플레이어 데이터 파일의 내용

**테스트 케이스 2**

확인 해야 하는것 :
> 플레이어가 1일차 보상을 받았을 때, 플레이어 데이터 파일의 ReceivedRewards 섹션에 day1 값이 생기는지의 여부
> 플레이어가 1일차 보상을 받은 이후, 한번 더 1일차 보상을 획득하려고 할때 보상 획득을 못 하는지의 여부

실행한 단계 :
> 1. 테스트 서버에 접속
> 2. "/출석체크" 명령어를 통해 출석체크의 GUI를 오픈.
> 3. GUI의 맨 왼쪽 위의 첫번째 칸에 있는 "1일차 보상"을 클릭하여 획득.
> 4. 한번 더 GUI의 맨 왼쪽 위의 첫번째 칸에 있는 "1일차 보상"을 클릭.

예상 결과 :
> 플레이어 데이터 파일의  ReceivedRewards 섹션에 day1 이라는 값이 생김.
> 플레이어는 2번 이상 같은 보상을 획득할 수 없음.

실제 결과 :
> 예상 결과랑 같은 결과가 나온 것을 확인. [통과]

첨부 사진 :
> ![image](https://user-images.githubusercontent.com/71818357/197182768-39caadb8-96fa-4b62-abf9-275d8fc1044e.png)
↑ 플레이어 데이터 파일의 ReceivedRewards 섹션에 day1이 생긴 결과
> ![image](https://user-images.githubusercontent.com/71818357/197182806-0a2c6a30-398b-4ce9-b039-c66a6022fe02.png)
↑ 게임 내에서 플레이어가 2번 이상 같은 보상을 획득 할 수 없다는 결과

**테스트 케이스 3**

확인 해야 하는것 :
> 날짜가 바뀐다음 플레이어가 다시 재접속을 하였을 때
> 플레이어 데이터 값의 LastJoinDate 섹션의 값이 재접속한 날짜로 변경되고
> CumulativeDate 섹션의 값이 1이 늘어나는지의 여부

실행한 단계 :
> 1. 테스트 서버에 첫 접속(접속한 날짜 2022-10-20)
> 2. 날짜가 바뀐뒤의 재접속 (재접속한 날짜 2022-10-21)

예상 결과 :
> 플레이어 데이터 파일의 LastJoinDate 섹션의 값이 재접속한 날짜인 2022-10-21로 바뀌며
> CumulativeDate 섹션의 값이 2가 됨.

실제 결과 :
> 예상 결과랑 같은 결과가 나온 것을 확인. [통과]

첨부 사진 :
> ![image](https://user-images.githubusercontent.com/71818357/197183699-2bb5d648-ce04-4180-be6c-b427cc99c4aa.png)
↑ 2022-10-20에 첫 접속했을 때의 플레이어 데이터 파일의 내용
> ![image](https://user-images.githubusercontent.com/71818357/197183800-6a31567e-aafa-4678-852f-25caf85ffbb8.png)
↑ 2022-10-21에 다시 접속했을 때의 플레이어 데이터 파일의 내용

**테스트 케이스 4**

확인 해야 하는 것 :
> 플레이어 데이터 파일의 CumulativeDate 섹션의 값에 따라 특정 일차 보상을 받을 수 있는지 없는지의 여부

실행한 단계 : 
> 1. 임의로 플러그인 폴더 내의 rewards.yml 파일 안에 1일차 보상, 2일차 보상, 3일차 보상들을 추가하여 테스트 서버 오픈.
> 2. 테스트 서버에 첫 접속(CumulativeDate 섹션의 값 : 1)
> 3. "/출석체크" 명령어를 통해 출석체크 GUI를 오픈.
> 4. 맨 왼쪽 위에서 부터 순차적으로 1일차 보상, 2일차 보상, 3일차 보상들을 클릭.
> 5. 날짜가 변한 뒤 테스트 서버에 재접속(CumulativeDate 섹션의 값 : 2)
> 6. 출석체크 GUI를 오픈하여 다시 순차적으로 1일차 보상, 2일차 보상, 3일차 보상들을 클릭.

예상 결과 :
> 첫 접속날에는 1일차 보상밖에 수령이 안되고, 2~3일차 보상은 수령이 안됨.
> 재접속날에는 1일차 보상은 첫 접속날에 이미 획득하여 수령이 안되고, 2일차 보상을 수령하고, 3일차 보상은 수령이 안됨.

실제 결과 :
> 예상 결과랑 같은 결과가 나온 것을 확인. [통과]

첨부 사진 :
> ![image](https://user-images.githubusercontent.com/71818357/197185335-bc8b91d5-bf8a-41df-89fe-97b6bf61db4a.png)
↑ 첫 접속날의 테스트 결과
> ![image](https://user-images.githubusercontent.com/71818357/197185569-d53224a2-8f6a-419a-9a1d-9c6dca063ef8.png)
↑ 날짜가 변한뒤 재 접속날의 테스트 결과

2022-10-21 13:14 UTC, Seokhun-Yang requested changes

2022-10-21 13:14 UTC, tjrhuni commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
> +                    createFolder();
플러그인을 리로드할 때 해당 메소드가 호출되는 이유가 무엇인가요? 매월 1일에 Players 폴더를 삭제하고 리로드 명령어를 통해 폴더를 재생성하는 것이 아닌 리붓을 통해서 Players 폴더를 생성하지 않을까요? 그리고 건즈 서버는 매일 오전 12시에 리붓하는 것으로 되어있으니 해당 메소드는 리로드 명령어에 필요하지 않은 메소드인 것 같습니다.

2022-10-21 13:14 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +    public FileConfiguration getRewardsFile() {
같은 메소드가 두 개 존재합니다. 하나는 제거해주세요.

2022-10-21 13:14 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +import org.bukkit.configuration.Configuration;
이 클래스의 23번 줄에 있는 dailyItemMetaSet에 값만 추가되고 사용되지 않고 있는데, 사용하지 않는 필드라면 제거해주세요.

2022-10-21 13:14 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +    }
이 클래스의 42번 줄에 있는 setGuiItems() 메소드는 존재하지 않는 메소드인 것 같은데 제거해주세요.

2022-10-21 13:14 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/Event.java
> +        ConfigurationSection section = loadConfigurationSection().getConfigurationSection(key);
if (section == null) return; 코드를 사용해서 section이 null인지 확인해주세요.

2022-10-21 13:28 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/Event.java
> +        ConfigurationSection section = loadConfigurationSection().getConfigurationSection(key);
Null 체크 추가했습니다.

2022-10-21 13:49 UTC, tjrhuni approved these changes

2022-10-22 11:28 UTC, kari0707 approved these changes

2022-10-22 13:28 UTC, LesserJang requested changes

2022-10-22 13:28 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/Event.java
> +                playerFile.save(file);
파일을 joinEvent에서 저장하게 되면 서버에 플레이어가 접속할때마다 파일을 저장하는 딜레이 때문에 서버가 잠깐잠깐씩 멈추게 됩니다. Bukkit.getScheduler().[runTaskAsynchronously](https://jd.papermc.io/paper/1.18/org/bukkit/scheduler/BukkitScheduler.html#runTaskAsynchronously(org.bukkit.plugin.Plugin,java.lang.Runnable))(Plugin plugin, Runnable task) 메소드를 이용해서 비동기로 파일을 저장해주세요

2022-10-22 13:28 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/PlayerDataManager.java
> +public class PlayerDataManager {
PlayerDataManager 클래스가 하는 일이 데이터파일 초기화밖에 없고, 이 클래스를 쓰는 곳도 joinEvent 한군데 밖에 없어요. 그럴바에 그냥 joinEvent에서 파일 초기화 하는게 더 좋을 것 같아요.

2022-10-23 11:36 UTC, LesserJang approved these changes

2022-10-23 11:36 UTC, merged