보상 GUI 아이템에 플레이어의 보상 수령, 미수령을 확인할 수 있는 로어 추가하기
MineFactory-Resource/DailyReward pull request #5
Opened 2022-10-24 11:45 UTC by Fade-Jung

**테스트 케이스의 테스트 환경 :**
> 1. 테스트 서버 버킷 : purpur-1.18.2-1632.jar
> 2. 테스트한 마인크래프트 버전 : 1.18.2

**테스트 케이스**

확인 해야 하는것:
> 플레이어가 "/출석체크" 명령어를 사용하여 인벤토리를 열었을 때,
> GUI 아이템 로어의 %rewards_receipt_status% 플레이스 홀더가 플레이어의 데이터 파일의 값에 따라
> 변경이 되는지 안되는지를 확인하기.

실행한 단계:
> 1. 플러그인 폴더 내의 rewards.yml 파일 안에 1일차 보상외의 여러보상들을 추가하여 테스트 서버 오픈.
> 2. 테스트 서버에 첫 접속 (CumulativeDate 섹션의 값 : 1)
> 3. "/출석체크" 명령어로 GUI를 열어 아이템들의 플레이스 홀더가 적용된 로어들을 확인
> 4. 1일차 보상을 획득한 후 다시 "/출석체크" 명령어로 GUI를 열어 아이템들의 플레이스 홀더가 적용된 로어들을 확인
> 5. 다음날 다시 재접속 (CumulativeDate 섹션의 값 : 2)
> 6. "/출석체크" 명령어로 GUI를 열어 아이템들의 플레이스 홀더가 적용된 로어들을 확인

예상한 결과:
> 1. 실행한 단계의 3번에서 1일차 보상 로어에는 "해당 일차보상을 수령할 수 있습니다." 라고 로어가 변경되고, 
> 그 이외 보상들의 로어는 "아직 해당 일차의 보상을 획득할 수 없다" 라고 로어가 변경되어야함. 
>
> 2. 실행한 단계의 4번에서 1일차 보상 로어에는 "이미 해당 일차보상을 수령했습니다." 라고 로어가 변경되고, 
> 그 이외 보상들의 로어는 "아직 해당 일차의 보상을 획득할 수 없다" 라고 로어가 변경되어야함. 
>
> 3. 실행한 단계의 6번에서 1일차 보상 로어에는 "이미 해당 일차보상을 수령했습니다." 라고 로어가 변경되고, 
> 2일차 보상 로어에는 "해당 일차보상을 수령할 수 있습니다." 라고 로어가 변경되고, 
> 그 이외 보상들의 로어는 "아직 해당 일차의 보상을 획득할 수 없다" 라고 로어가 변경되어야함.

실제 결과 :
> 예상한 결과랑 같은 결과가 나온것을 확인 [통과]

첨부 사진 : 
> ![image](https://user-images.githubusercontent.com/71818357/197517764-48c1cbb7-7479-44b9-b26a-be5ebdd70470.png)
> ↑ 실행한 단계 3번에서 1일차 보상 로어의 모습
> ![image](https://user-images.githubusercontent.com/71818357/197517839-e0363c01-148f-460c-9e06-5d8334679ce4.png)
> ↑ 실행한 단계 4번에서 1일차 보상 로어의 모습
> ![image](https://user-images.githubusercontent.com/71818357/197518164-4605529d-102e-4f6d-97fa-3841ee29361f.png)
> ↑ 실행한 단계 6번에서 2일차 보상 로어의 모습
> ![image](https://user-images.githubusercontent.com/71818357/197517902-31cdd253-e3c9-47da-aa06-4b2912396fce.png)
> ↑ 실행한 단계 3,4,6번에서 그 이외 보상들의 로어의 모습

2022-10-25 08:03 UTC, kari0707 commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +        File file = new File("plugins/Dailyreward/Players", uuid + ".yml");
메인 클래스에서 변수를 가져오는 것보단 매개변수를 활용하시는 게 더 좋아 보여요

2022-10-26 11:13 UTC, LesserJang requested changes

2022-10-26 11:13 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +    public void setGui(UUID uuid) {
지금 RewardManager 클래스의 구조 자체가 뭔가 이상한 것 같습니다. 지금 보면 onCommand 메소드에서 setGui 메소드로 플레이어의 UUID 를 건네주면 이 클래스의 dailyRewardGui 변수에 해당 플레이어의 아이템들을 담고, 다시 onCommand 메소드에서 클래스의 인스턴스 변수에 직접 접근해서 인벤토리를 열어주고 있습니다. RewardManager 클래스는 사실상singleton(객체를 한개만 만들어놓고 사용하는 것) 클래스인데, 사용자가 호출할때마다 계속 싱글톤의 인스턴스 변수에다가 해당 사용자의 아이템을 담아서 보여주는 사실상 임시 변수처럼 쓰이고 있어요. 이러면 구조상 되게 보기 안좋은것 뿐만 아니라 메모리 누수도 일어날 수 있습니다. 따로 openGui 메소드를 만들어서 인벤토리를 미리 만들어두지 않고 그때그떄마다 만드는게 더 좋을 것 같아요.

2022-10-27 08:22 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +    public void setGui(UUID uuid) {
```
  public void openGui(Player player){
        setGui(player.getUniqueId());
        player.openInventory(this.dailyRewardGui);
    }
```
이런식으로 openGui메소드를 만들고,
onCommand 메소드에서 openGui 메소드로 플레이어를 건네주게끔 만들기는 했는데
혹시 제가 한 방식이 틀린게 있는지 확인해 주실 수 있나요?

2022-10-27 08:40 UTC, LesserJang requested changes

2022-10-27 08:40 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/RewardManager.java
> +    public void setGui(UUID uuid) {
궁극적으로, dailyRewardGui 변수가 사라지셔야 합니다.. 제가 했던 말의 뜻은 객체가 딱 한번 만들어져서 사용되는 클래스의 변수를 마치 임시변수처럼 쓰이고 있어서 문제라고 했던겁니다. setGui 없애시고 openGui에서 호출될때마다 createInventory 메소드를 사용해서 인벤토리를 생성하세요.

2022-10-27 09:31 UTC, LesserJang approved these changes

2022-10-27 10:58 UTC, Seokhun-Yang approved these changes

2022-10-27 11:33 UTC, merged