코드 구조 수정하기
MineFactory-Resource/DailyReward pull request #8
Opened 2022-11-04 10:29 UTC by Fade-Jung

**기존 DailyReward 플러그인 클래스의 코드 구조의 문제들을 다음과 같이 수정하였습니다.**

1. **DailyReward에 중복되는 코드들이 존재함.** 

    => 중복되는 코드들을 묶어서 메소드를 만들뒤에 그 코드를 사용하는 함수에서 호출하는식으로 수정하였습니다.
    
2. **DailyReward에서 함수와, 매개변수의 활용이 적음** 

    => 메소드와 매개변수를 활용하고, 이를 호출하여 중요한 메소드의 코드를 줄였습니다.
    
3. **DailyReward의 전역변수가, 선언된 클래스 내에서만 사용하는데 전역변수가 의미없이 
    public으로 하여 모든 클래스에서 접근이 가능하게끔 해버림.** 
    
    => 선언된 클래스안에서 사용하는 것들은 private, 다른 클래스에서 접근이 필요한 것들은 public으로 수정하였습니다.
    
4. **DailyReward의 함수에서 함수명에 맞지않는 역할을 수행하는 함수가 있음.**

    => 함수명에 맞지 않는 역할을 수행하는 함수를 그 역할에 맞는 함수로 수정을 하였으며
          필요에 따라 새롭게 함수명을 수정했습니다.

2022-11-04 11:01 UTC, LesserJang requested changes

2022-11-04 11:01 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
>      }
전혀 쓸모 없는 메소드입니다. 자기 자신을 반환하는데 그냥 안쓰고 말지 왜 이런 메소드가 필요한가요? 이 메소드를 쓰는 것 자체가 이상합니다.

2022-11-04 11:01 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
>      public Dailyreward plugin;
자기 자신을 저장하는 변수는 쓸모 없는 변수입니다. 어짜피 자기 자신을 저장할거면 그냥 this 쓰고말지 왜 plugin 변수를 쓰나요?

2022-11-04 11:01 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/Event.java
> +
만약 플레이어가 이미 OP인 상태로 커맨드를 실행하면 실행이 끝나고 setOp(false) 때문에 오피 권한이 빠져버립니다. 오피 권한이 이미 있는 경우와 없는 경우를 나누셔야 됩니다.

2022-11-04 11:05 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
>      }
이것에 역할은 무엇이고 왜 필요함?

2022-11-04 11:05 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/Dailyreward.java
>              try {
폴더 생성시키는게 로드될때만 할거라고 확신할 수 있나?

2022-11-06 11:43 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/config/RewardFileManager.java
> +    }
무언가 단단히 착각하고 진행하고 있는데 "생각하고" 코드 짜세요
이게 무엇에 필요한 함수인가요?

2022-11-06 11:43 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/command/DailyRewardCommand.java
> +    }
설명 부탁함

2022-11-06 11:44 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/gui/RewardManager.java
> +        Set<String> rewardsKeys = section.getKeys(false);
설명 부탁함

2022-11-06 11:45 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/gui/RewardManager.java
> +        }
설명 부탁함, try로 감싼 이유는?

2022-11-06 11:45 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/gui/RewardManager.java
> +    private List<String> rewardLore(ConfigurationSection section, String key, UUID uuid) {
설명 부탁함, 뭐하는 함수인지 모르겠네

2022-11-06 11:45 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/gui/DailyRewardGui.java
> +    }
설명 부탁함

2022-11-06 11:45 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/gui/DailyRewardGui.java
> +    private final DailyReward main;
설명 부탁함

2022-11-06 11:45 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/event/JoinEvent.java
> +    }
설명 부탁함

2022-11-06 11:46 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/event/DragEvent.java
> +        event.setCancelled(true);
"ChatColor.GREEN + "출석체크 GUI" 이면 드래그 이벤트 취소로 알고 있는데 왜 이런식으로 되었지?

2022-11-06 11:47 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/event/DragEvent.java
> +        event.setCancelled(true);
"ChatColor.GREEN + "출석체크 GUI" 가 아니면 다른 GUI 전부 취소. 로 보이는데?

2022-11-06 11:47 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/event/ClickEvent.java
> +        event.setCancelled(true);
마찬가지

2022-11-06 11:52 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/gui/RewardManager.java
> +        }
코드를 나누던 중에 꼼꼼히 확인을 안하고 삭제를 안했습니다. 삭제 조치 하도록 하겠습니다.

2022-11-06 11:55 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/gui/RewardManager.java
> +    private List<String> rewardLore(ConfigurationSection section, String key, UUID uuid) {
reward.yml 파일에서 보상의 로어에 %rewards_receipt_status% 가 포함되어 있으면 
이를 플레이어의 상태에 따라 로어를 3가지로 변경이 된후, 색코드가 적용되게끔 해주고
포함되어 있지않으면 로어를 색코드가 적용되게끔 해주는 함수입니다.

2022-11-06 12:40 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/event/DragEvent.java
> +        event.setCancelled(true);
GUI의 타이틀이 "ChatColor.GREEN + "출석체크 GUI" 가 아니라면 해당 함수를 바로 끝나게끔 하고
GUI의 타이틀이 "ChatColor.GREEN + "출석체크 GUI" 라면 드래그나 클릭 이벤트를 취소시키는것을 목적으로 하였습니다.

2022-11-07 10:48 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/config/RewardFileManager.java
> +    }
getSection은 불필요하고 무의미한 함수였습니다. 
해당 함수는 코드에서 삭제를 하였으며, 해당 함수를 사용했었던 코드들도 수정을 하였습니다.

2022-11-07 11:42 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/gui/RewardManager.java
> +        Set<String> rewardsKeys = section.getKeys(false);
section에 포함된 키들의 집합을 집합 자료형인 rewardsKeys 에 대입해주는 코드입니다.

2022-11-12 09:22 UTC, LesserJang requested changes

2022-11-12 09:22 UTC, LesserJang commented on src/main/java/net/teamuni/dailyreward/event/DragEvent.java
> +public class DragEvent implements Listener {
ClickEvent와 DragEvent 모두 인벤토리 이벤트 처리를 하는 클래스인데 ClickEvent 클래스와 쓸데 없이 나누어져 있어요. 합치는게 더 좋을 것 같아요.

2022-11-12 09:31 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/event/DragEvent.java
> +public class DragEvent implements Listener {
DragEvent를 ClickEvent에다 병합하고, ClickEvent의 클래스명을 InventoryEvent로 리팩토링했습니다.

2022-11-12 12:30 UTC, LesserJang approved these changes

2022-11-12 14:14 UTC, Seokhun-Yang approved these changes

2022-11-12 14:14 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/dailyreward/command/DailyRewardCommand.java
> +import org.bukkit.ChatColor;
불필요한 import 제거해주시면 좋을 것 같아요

2022-11-13 04:41 UTC, abelbeak commented on src/main/java/net/teamuni/dailyreward/DailyReward.java
> +        this.dailyRewardCommand = new DailyRewardCommand(this);
이거는 왜 필요한거임?

2022-11-13 06:04 UTC, kari0707 commented on src/main/java/net/teamuni/dailyreward/config/ConfigManager.java
> +        }
이 코드를 메소드로 만들고 사용하시는게 더 나을 거 같아요.

2022-11-13 06:04 UTC, kari0707 commented on src/main/java/net/teamuni/dailyreward/config/ConfigManager.java
> +    }
위에서 file 이 null이면 새로 정의를 해주는데, 마지막에 다시 정의를 하는 코드가 있어요.
마지막 코드는 지워주시는 게 좋을 거 같아요

2022-11-13 06:04 UTC, kari0707 commented on src/main/java/net/teamuni/dailyreward/config/RewardFileManager.java
> +    }
마찬가지로 ConfigManager랑 같이 수정해주세요.

2022-11-13 07:42 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/config/ConfigManager.java
> +        }
코드에서 defineFile 이라는 메소드를 만들어 추가했습니다.

2022-11-13 07:43 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/config/ConfigManager.java
> +    }
삭제 조치하였습니다.

2022-11-13 07:52 UTC, Fade-Jung commented on src/main/java/net/teamuni/dailyreward/DailyReward.java
> +        this.dailyRewardCommand = new DailyRewardCommand(this);
각 클래스에 있는 생성자들을 호출해주는 역할입니다.

2022-11-13 10:02 UTC, kari0707 approved these changes

2022-11-13 10:18 UTC, merged